apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sifnode.fullname" . }}
  labels:
{{ include "sifnode.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sifnode.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sifnode.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
