apiVersion: v1
kind: Service
metadata:
  name: {{ include "sifnode.fullname" . }}
  labels:
    {{- include "sifnode.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.sifnode.args.enableAPI }}
    - port: 1317
      protocol: TCP
      name: api
    {{- end }}
    {{- if .Values.sifnode.args.enableGrpc }}
    - port: 9090
      protocol: TCP
      name: grpc
    {{- end }}
    - port: 26656
      protocol: TCP
      name: p2p
    - port: 26657
      protocol: TCP
      name: rpc
  selector:
    {{- include "sifnode.selectorLabels" . | nindent 4 }}
