name: Docker

on: [workflow_dispatch] 

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: sifdocker

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
 
      - name: Build image
        run: cd test/integration/vagrant; make sifdocker

      - name: Log into registry
        run: echo "${{ secrets.GITREPO }}" | docker login https://docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin

      - name: Push image
        run: docker push ghcr.io/gboie/$IMAGE_NAME:latest
