name: Publish Mainnet Images

on:
  release:
    type: created
    branches: master

jobs:
  mainnet:
    name: mainnet
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |
          make CHAINNET=mainnet BINARY=sifnoded build-image
          make CHAINNET=mainnet BINARY=sifnodecli build-image
          make CHAINNET=mainnet BINARY=sifcrg build-image
          cd ./api/openapi & make CHAINNET=mainnet build-image-swagger-iu

      - name: Push images
        run: |
          docker push sifchain/sifnoded:mainnet
          docker push sifchain/sifnodecli:mainnet
          docker push sifchain/sifcrg:mainnet
          docker push sifchain/swagger-ui:mainnet

