name: Pull Request Checks

on:
  pull_request:
    branches:
      - develop

jobs:
  slither:
    name: slither
    runs-on: ubuntu-latest
    steps:
      - name: Install Node and Yarn
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'
      - run: |
          npm install -g yarn
          
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Python Dependencies
        run: |
          sudo apt-get install python3-setuptools
          sudo apt-get install gcc libpq-dev -y
          sudo apt-get install python-dev  python-pip -y
          sudo apt-get install python3-dev python3-pip python3-setuptools python3-venv python3-wheel -y
          
      - name: Install Dependencies
        run: |
          git clone https://github.com/crytic/solc-select.git
          ./solc-select/scripts/install.sh
          export PATH=/home/runner/.solc-select:$PATH
          echo "export PATH=/home/runner/.solc-select:$PATH" >> ~/.bashrc
      
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Run Slither
        working-directory: ./smart-contracts
        run: |
          /home/runner/.solc-select/solc use 0.5.12
          pip install -r requirements.txt
          pip install slither-analyzer --user
          yarn
          slither . --print human-summary > ../slither_results.txt
      
      - name: Upload Results as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Slither Results
          path: slither_results.txt
